"""Parse LLM responses into executable Action objects.

ResponseParser converts the ``tool_calls`` of an ``LLMResponse`` into
``Action`` instances for the harness loop.  Each tool call is a dict in
the codebase convention ``{"name": ..., "params": ...}`` (as produced by
the DeepSeek/Mock backends); calls whose name is empty or missing are
dropped so the loop only ever executes well-formed actions.  Action IDs
are auto-generated by the Action dataclass, so every parse yields fresh,
unique IDs per action.
"""
from __future__ import annotations

from codeharness.models import Action, LLMResponse


class ResponseParser:
    """Convert LLMResponse tool calls into a list of Action objects."""

    def parse(self, response: LLMResponse) -> list[Action]:
        """Map each tool call to an Action, skipping empty tool names."""
        actions: list[Action] = []
        for call in response.tool_calls:
            name = call.get("name")
            if not name:
                continue
            params = call.get("params") or {}
            actions.append(Action(tool=name, params=params))
        return actions
